# Generated by Django 5.0.3 on 2024-03-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Maqola nomi')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('published', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('image', models.ImageField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ('-pk',),
            },
        ),
    ]
